services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: galaxy-postgres
    environment:
      POSTGRES_DB: galaxy_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: galaxy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Commander (Web UI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: galaxy-redis-commander
    environment:
      REDIS_HOSTS: local:localhost:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    network_mode: "host"

  # pgAdmin (Optional - Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: galaxy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@galaxy.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    network_mode: "host"

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: